//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WS_POS_web.wsGetInfoCliente {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    // CODEGEN: No se controló el elemento de extensión WSDL opcional 'Policy' del espacio de nombres 'http://schemas.xmlsoap.org/ws/2004/09/policy'.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ZWS_DATOS_CLIENTE_POSWEB", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZWS_DATOS_CLIENTE_POSWEBService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ZfiDatosClientePos2023OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ZWS_DATOS_CLIENTE_POSWEBService() {
            this.Url = global::WS_POS_web.Properties.Settings.Default.WS_POS_web_wsGetInfoCliente_ZWS_DATOS_CLIENTE_POSWEBService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ZfiDatosClientePos2023CompletedEventHandler ZfiDatosClientePos2023Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="urn:sap-com:document:sap:soap:functions:mc-style", ResponseNamespace="urn:sap-com:document:sap:soap:functions:mc-style", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ECabCliente", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ZestNpCabCliente ZfiDatosClientePos2023([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string PStcd1, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out int ESubrc) {
            object[] results = this.Invoke("ZfiDatosClientePos2023", new object[] {
                        PStcd1});
            ESubrc = ((int)(results[1]));
            return ((ZestNpCabCliente)(results[0]));
        }
        
        /// <remarks/>
        public void ZfiDatosClientePos2023Async(string PStcd1) {
            this.ZfiDatosClientePos2023Async(PStcd1, null);
        }
        
        /// <remarks/>
        public void ZfiDatosClientePos2023Async(string PStcd1, object userState) {
            if ((this.ZfiDatosClientePos2023OperationCompleted == null)) {
                this.ZfiDatosClientePos2023OperationCompleted = new System.Threading.SendOrPostCallback(this.OnZfiDatosClientePos2023OperationCompleted);
            }
            this.InvokeAsync("ZfiDatosClientePos2023", new object[] {
                        PStcd1}, this.ZfiDatosClientePos2023OperationCompleted, userState);
        }
        
        private void OnZfiDatosClientePos2023OperationCompleted(object arg) {
            if ((this.ZfiDatosClientePos2023Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZfiDatosClientePos2023Completed(this, new ZfiDatosClientePos2023CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZestNpCabCliente {
        
        private string codigoSapField;
        
        private string cedulaRucField;
        
        private string tipoIdentificacionField;
        
        private string apellidosField;
        
        private string nombresField;
        
        private string grpCtaClienteField;
        
        private string grupoClienteField;
        
        private string codProvinciaField;
        
        private string textoProvinciaField;
        
        private string poblacionField;
        
        private string textoPoblacionField;
        
        private string distritoField;
        
        private string textoDistritoField;
        
        private string calleField;
        
        private string paisField;
        
        private string codGeneroField;
        
        private string textoGeneroField;
        
        private string codTratamientoField;
        
        private string textoTratamientoField;
        
        private string codEstadoCivilField;
        
        private string textoEstadoCivilField;
        
        private string actividadEconomicaField;
        
        private string textoActEconomicaField;
        
        private string correoField;
        
        private string telefono1Field;
        
        private string telefono2Field;
        
        private string deudaField;
        
        private string codRamoField;
        
        private string textoRamoField;
        
        private string codRamo1Field;
        
        private string textoRamo1Field;
        
        private string bloqCreditoField;
        
        private string fecNacimientoField;
        
        private string limiteCreditoField;
        
        private string saldoClienteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodigoSap {
            get {
                return this.codigoSapField;
            }
            set {
                this.codigoSapField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CedulaRuc {
            get {
                return this.cedulaRucField;
            }
            set {
                this.cedulaRucField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TipoIdentificacion {
            get {
                return this.tipoIdentificacionField;
            }
            set {
                this.tipoIdentificacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Apellidos {
            get {
                return this.apellidosField;
            }
            set {
                this.apellidosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GrpCtaCliente {
            get {
                return this.grpCtaClienteField;
            }
            set {
                this.grpCtaClienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GrupoCliente {
            get {
                return this.grupoClienteField;
            }
            set {
                this.grupoClienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodProvincia {
            get {
                return this.codProvinciaField;
            }
            set {
                this.codProvinciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TextoProvincia {
            get {
                return this.textoProvinciaField;
            }
            set {
                this.textoProvinciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Poblacion {
            get {
                return this.poblacionField;
            }
            set {
                this.poblacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TextoPoblacion {
            get {
                return this.textoPoblacionField;
            }
            set {
                this.textoPoblacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Distrito {
            get {
                return this.distritoField;
            }
            set {
                this.distritoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TextoDistrito {
            get {
                return this.textoDistritoField;
            }
            set {
                this.textoDistritoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Calle {
            get {
                return this.calleField;
            }
            set {
                this.calleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Pais {
            get {
                return this.paisField;
            }
            set {
                this.paisField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodGenero {
            get {
                return this.codGeneroField;
            }
            set {
                this.codGeneroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TextoGenero {
            get {
                return this.textoGeneroField;
            }
            set {
                this.textoGeneroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodTratamiento {
            get {
                return this.codTratamientoField;
            }
            set {
                this.codTratamientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TextoTratamiento {
            get {
                return this.textoTratamientoField;
            }
            set {
                this.textoTratamientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodEstadoCivil {
            get {
                return this.codEstadoCivilField;
            }
            set {
                this.codEstadoCivilField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TextoEstadoCivil {
            get {
                return this.textoEstadoCivilField;
            }
            set {
                this.textoEstadoCivilField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ActividadEconomica {
            get {
                return this.actividadEconomicaField;
            }
            set {
                this.actividadEconomicaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TextoActEconomica {
            get {
                return this.textoActEconomicaField;
            }
            set {
                this.textoActEconomicaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Telefono1 {
            get {
                return this.telefono1Field;
            }
            set {
                this.telefono1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Telefono2 {
            get {
                return this.telefono2Field;
            }
            set {
                this.telefono2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Deuda {
            get {
                return this.deudaField;
            }
            set {
                this.deudaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodRamo {
            get {
                return this.codRamoField;
            }
            set {
                this.codRamoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TextoRamo {
            get {
                return this.textoRamoField;
            }
            set {
                this.textoRamoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodRamo1 {
            get {
                return this.codRamo1Field;
            }
            set {
                this.codRamo1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TextoRamo1 {
            get {
                return this.textoRamo1Field;
            }
            set {
                this.textoRamo1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BloqCredito {
            get {
                return this.bloqCreditoField;
            }
            set {
                this.bloqCreditoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FecNacimiento {
            get {
                return this.fecNacimientoField;
            }
            set {
                this.fecNacimientoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LimiteCredito {
            get {
                return this.limiteCreditoField;
            }
            set {
                this.limiteCreditoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SaldoCliente {
            get {
                return this.saldoClienteField;
            }
            set {
                this.saldoClienteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ZfiDatosClientePos2023CompletedEventHandler(object sender, ZfiDatosClientePos2023CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZfiDatosClientePos2023CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZfiDatosClientePos2023CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ZestNpCabCliente Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ZestNpCabCliente)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public int ESubrc {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591