//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_POS_web.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ajeprd.eljuric.com:8000/sap/bc/srt/rfc/sap/zsdws_pos_consulta_vendedores/4" +
            "00/zsdws_pos_consulta_vendedores/zsdws_pos_consulta_vendedores_binding")]
        public string WS_POS_web_Ws_obt_vend_PRD_ZSDWS_POS_CONSULTA_VENDEDORES {
            get {
                return ((string)(this["WS_POS_web_Ws_obt_vend_PRD_ZSDWS_POS_CONSULTA_VENDEDORES"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://AJEQAS:8000/sap/bc/srt/rfc/sap/zsdws_pos_consulta_vendedores/400/zsdws_pos" +
            "_consulta_vendedores/zsdws_pos_consulta_vendedores_binding")]
        public string WS_POS_web_Ws_obt_vend_ZSDWS_POS_CONSULTA_VENDEDORES {
            get {
                return ((string)(this["WS_POS_web_Ws_obt_vend_ZSDWS_POS_CONSULTA_VENDEDORES"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ajeprd.eljuric.com:8000/sap/bc/srt/rfc/sap/zsdws_pos_consulta_clientes/400" +
            "/zsdws_pos_consulta_clientes/zsdws_pos_consulta_clientes_binding")]
        public string WS_POS_web_Ws_Get_Cliente_PRD_ZSDWS_POS_CONSULTA_CLIENTES {
            get {
                return ((string)(this["WS_POS_web_Ws_Get_Cliente_PRD_ZSDWS_POS_CONSULTA_CLIENTES"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ajeprd.eljuric.com:8000/sap/bc/srt/rfc/sap/zws_precio_desc_financiamiento/" +
            "400/zws_precio_desc_financiamiento/binding1")]
        public string WS_POS_web_Ws_Financiamiento_PRD_ZWS_PRECIO_DESC_FINANCIAMIENTO {
            get {
                return ((string)(this["WS_POS_web_Ws_Financiamiento_PRD_ZWS_PRECIO_DESC_FINANCIAMIENTO"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://AJEQAS:8000/sap/bc/srt/rfc/sap/zws_precio_desc_financiamiento/400/zws_prec" +
            "io_desc_financiamiento/zws_precio_desc_financiamiento_binding")]
        public string WS_POS_web_Ws_Financiamiento_ZWS_PRECIO_DESC_FINANCIAMIENTO {
            get {
                return ((string)(this["WS_POS_web_Ws_Financiamiento_ZWS_PRECIO_DESC_FINANCIAMIENTO"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://AJEQAS:8000/sap/bc/srt/rfc/sap/zsdws_pos_consulta_clientes/400/zsdws_pos_c" +
            "onsulta_clientes/zsdws_pos_consulta_clientes_binding")]
        public string WS_POS_web_Ws_Get_Cliente_ZSDWS_POS_CONSULTA_CLIENTES {
            get {
                return ((string)(this["WS_POS_web_Ws_Get_Cliente_ZSDWS_POS_CONSULTA_CLIENTES"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://AJEQAS:8000/sap/bc/srt/rfc/sap/zws_items_valores_factura/400/zws_items_val" +
            "ores_factura/zws_items_valores_factura")]
        public string WS_POS_web_Ws_Precios_Materiales_ZWS_ITEMS_VALORES_FACTURAService {
            get {
                return ((string)(this["WS_POS_web_Ws_Precios_Materiales_ZWS_ITEMS_VALORES_FACTURAService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ajeprd.eljuric.com:8000/sap/bc/srt/rfc/sap/zws_creater_costumer_2010/400/z" +
            "ws_creater_costumer_2010/zws_creater_costbinding")]
        public string WS_POS_web_Ws_Creacion_Cliente_N_PRD_ZWS_CREATER_COSTUMER_2010 {
            get {
                return ((string)(this["WS_POS_web_Ws_Creacion_Cliente_N_PRD_ZWS_CREATER_COSTUMER_2010"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://AJEQAS:8000/sap/bc/srt/rfc/sap/zws_creater_costumer_2010/400/zws_creater_c" +
            "ostumer_2010/zws_creater_costbinding")]
        public string WS_POS_web_Ws_Creacion_Cliente_N_ZWS_CREATER_COSTUMER_2010 {
            get {
                return ((string)(this["WS_POS_web_Ws_Creacion_Cliente_N_ZWS_CREATER_COSTUMER_2010"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ajeprd.eljuric.com:8000/sap/bc/srt/rfc/sap/zsdws_pos_consulta_material3/40" +
            "0/zsdws_pos_consulta_material3/binding")]
        public string WS_POS_web_Ws_Get_Material_PRD_ZSDWS_POS_CONSULTA_MATERIAL3 {
            get {
                return ((string)(this["WS_POS_web_Ws_Get_Material_PRD_ZSDWS_POS_CONSULTA_MATERIAL3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://AJEQAS:8000/sap/bc/srt/rfc/sap/zsdws_pos_consulta_material3/400/zsdws_pos_" +
            "consulta_material3/zsdws_pos_consulta_material3_binding")]
        public string WS_POS_web_Ws_Get_Material_ZSDWS_POS_CONSULTA_MATERIAL3 {
            get {
                return ((string)(this["WS_POS_web_Ws_Get_Material_ZSDWS_POS_CONSULTA_MATERIAL3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ajeprd.eljuric.com:8000/sap/bc/srt/rfc/sap/zws_amplia_cliente_tablet/400/z" +
            "ws_amplia_cliente_tablet/zws_amplia_cliente_tablet_binding")]
        public string WS_POS_web_Ws_Ampliacion_PRD_ZWS_AMPLIA_CLIENTE_TABLET {
            get {
                return ((string)(this["WS_POS_web_Ws_Ampliacion_PRD_ZWS_AMPLIA_CLIENTE_TABLET"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://AJEQAS:8000/sap/bc/srt/rfc/sap/zws_consulta_combos_tablet/400/zws_consulta" +
            "_combos_tablet/zws_consulta_combos_tablet_binding")]
        public string WS_POS_web_Ws_Combos_ZWS_CONSULTA_COMBOS_TABLET {
            get {
                return ((string)(this["WS_POS_web_Ws_Combos_ZWS_CONSULTA_COMBOS_TABLET"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ajeprd.eljuric.com:8000/sap/bc/srt/rfc/sap/zws_consulta_combos_tablet/400/" +
            "zws_consulta_combos_tablet/zws_consulta_combos_tablet_binding")]
        public string WS_POS_web_Ws_Combos_PRD_ZWS_CONSULTA_COMBOS_TABLET {
            get {
                return ((string)(this["WS_POS_web_Ws_Combos_PRD_ZWS_CONSULTA_COMBOS_TABLET"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ajeprd.eljuric.com:8000/sap/bc/srt/rfc/sap/zws_sdnetpr0_cep/400/zws_sdnetp" +
            "r0_cep/zws_sdnetpr0_cep_binding")]
        public string WS_POS_web_Ws_Precios_cep_PRD_ZWS_SDNETPR0_CEP {
            get {
                return ((string)(this["WS_POS_web_Ws_Precios_cep_PRD_ZWS_SDNETPR0_CEP"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://AJEQAS:8000/sap/bc/srt/rfc/sap/zws_sdnetpr0_cep/400/zws_sdnetpr0_cep/zws_s" +
            "dnetpr0_cep_binding")]
        public string WS_POS_web_Ws_Precios_cep_ZWS_SDNETPR0_CEP {
            get {
                return ((string)(this["WS_POS_web_Ws_Precios_cep_ZWS_SDNETPR0_CEP"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ajeprd.eljuric.com:8000/sap/bc/srt/rfc/sap/zws_sdnetpr0/400/zws_sdnetpr0/z" +
            "ws_sdnetpr0_binding")]
        public string WS_POS_web_Ws_Get_Material__Price_PRD_ZWS_SDNETPR0 {
            get {
                return ((string)(this["WS_POS_web_Ws_Get_Material__Price_PRD_ZWS_SDNETPR0"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ajeprd.eljuric.com:8000/sap/bc/srt/rfc/sap/zsd_ws_caracteriscita_mat/400/z" +
            "sd_ws_caracteriscita_mat/binding")]
        public string WS_POS_web_Ws_CaractMat_PRD_ZSD_WS_CARACTERISCITA_MAT {
            get {
                return ((string)(this["WS_POS_web_Ws_CaractMat_PRD_ZSD_WS_CARACTERISCITA_MAT"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://AJEQAS:8000/sap/bc/srt/rfc/sap/zsd_ws_caracteriscita_mat/400/zsd_ws_caract" +
            "eriscita_mat/zsd_ws_caracteriscita_mat_binding")]
        public string WS_POS_web_Ws_CaractMat_ZSD_WS_CARACTERISCITA_MAT {
            get {
                return ((string)(this["WS_POS_web_Ws_CaractMat_ZSD_WS_CARACTERISCITA_MAT"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://AJEQAS:8000/sap/bc/srt/rfc/sap/zws_material_lote_serie_alma/400/zws_materi" +
            "al_lote_serie_alma/zws_material_lote_serie_alma_binding")]
        public string WS_POS_web_Ws_material_lote_serie_alma_ZWS_MATERIAL_LOTE_SERIE_ALMA {
            get {
                return ((string)(this["WS_POS_web_Ws_material_lote_serie_alma_ZWS_MATERIAL_LOTE_SERIE_ALMA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ajeprd.eljuric.com:8000/sap/bc/srt/rfc/sap/zws_material_lote_serie_alma/40" +
            "0/zws_material_lote_serie_alma/zws_material_lote_serie_alma_binding")]
        public string WS_POS_web_Ws_material_lote_serie_alma_PRD_ZWS_MATERIAL_LOTE_SERIE_ALMA {
            get {
                return ((string)(this["WS_POS_web_Ws_material_lote_serie_alma_PRD_ZWS_MATERIAL_LOTE_SERIE_ALMA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://AJEQAS:8000/sap/bc/srt/rfc/sap/zws_datos_cliente_posweb/400/zws_datos_clie" +
            "nte_posweb/zws_datos_cliente_posweb")]
        public string WS_POS_web_wsGetInfoCliente_ZWS_DATOS_CLIENTE_POSWEBService {
            get {
                return ((string)(this["WS_POS_web_wsGetInfoCliente_ZWS_DATOS_CLIENTE_POSWEBService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ajeprd.eljuric.com:8000/sap/bc/srt/rfc/sap/zws_consultar_provincias/400/zw" +
            "s_consultar_provincias/zws_consultar_provincias_binding")]
        public string WS_POS_web_wsGetProvCiudParr_PRD_ZWS_CONSULTAR_PROVINCIAS {
            get {
                return ((string)(this["WS_POS_web_wsGetProvCiudParr_PRD_ZWS_CONSULTAR_PROVINCIAS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ajeprd.eljuric.com:8000/sap/bc/srt/rfc/sap/zws_lista_subramos/400/zws_list" +
            "a_subramos/zws_lista_subramos_binding")]
        public string WS_POS_web_wsGetSubramo_PRD_ZWS_LISTA_SUBRAMOS {
            get {
                return ((string)(this["WS_POS_web_wsGetSubramo_PRD_ZWS_LISTA_SUBRAMOS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ajeprd.eljuric.com:8000/sap/bc/srt/rfc/sap/zws_add_upd_cliente/400/zws_add" +
            "_upd_cliente/zws_add_upd_cliente_binding")]
        public string WS_POS_web_wsAddUpdCliente_ZWS_ADD_UPD_CLIENTE {
            get {
                return ((string)(this["WS_POS_web_wsAddUpdCliente_ZWS_ADD_UPD_CLIENTE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.10.3.13/wsBilleteraCoopCrea/wsBilletera.asmx")]
        public string WS_POS_web_Ws_ValidateCreaAccount_PRD_MetodosBilletera {
            get {
                return ((string)(this["WS_POS_web_Ws_ValidateCreaAccount_PRD_MetodosBilletera"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ajeprd.eljuric.com:8000/sap/bc/srt/rfc/sap/zws_get_anticipo_cliente/400/zw" +
            "s_get_anticipo_cliente/zws_get_anticipo_cliente_binding")]
        public string WS_POS_web_Ws_Anticipos_PRD_ZWS_GET_ANTICIPO_CLIENTE {
            get {
                return ((string)(this["WS_POS_web_Ws_Anticipos_PRD_ZWS_GET_ANTICIPO_CLIENTE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ajeprd.eljuric.com:8000/sap/bc/srt/rfc/sap/zsdws_pos_consulta_cupo_cred/40" +
            "0/zsdws_pos_consulta_cupo_cred/zsdws_pos_consulta_cupo_cred_binding")]
        public string WS_POS_web_Ws_CupoCliente_PRD_ZSDWS_POS_CONSULTA_CUPO_CRED {
            get {
                return ((string)(this["WS_POS_web_Ws_CupoCliente_PRD_ZSDWS_POS_CONSULTA_CUPO_CRED"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ajeprd.eljuric.com:8000/sap/bc/srt/rfc/sap/zws_consulta_bank/400/zws_consu" +
            "lta_bank/zws_consulta_bank")]
        public string WS_POS_web_Ws_Cuenta_Digitos_PRD_ZWS_CONSULTA_BANK {
            get {
                return ((string)(this["WS_POS_web_Ws_Cuenta_Digitos_PRD_ZWS_CONSULTA_BANK"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ajeprd.eljuric.com:8000/sap/bc/srt/rfc/sap/zws_consulta_gifcard/400/zws_co" +
            "nsulta_gifcard/zws_consulta_gifcard_binding")]
        public string WS_POS_web_Ws_Consulta_GiftCard_PRD_ZWS_CONSULTA_GIFCARD {
            get {
                return ((string)(this["WS_POS_web_Ws_Consulta_GiftCard_PRD_ZWS_CONSULTA_GIFCARD"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ajeprd.eljuric.com:8000/sap/bc/srt/rfc/sap/zds_buscar_clie_nom/400/zds_bus" +
            "car_clie_nom/zds_buscar_clie_nom_binding")]
        public string WS_POS_web_Ws_Get_Clientes_Nombre_PRD_ZDS_BUSCAR_CLIE_NOM {
            get {
                return ((string)(this["WS_POS_web_Ws_Get_Clientes_Nombre_PRD_ZDS_BUSCAR_CLIE_NOM"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ajeprd.eljuric.com:8000/sap/bc/srt/rfc/sap/zsdws_pos_consulta_combos/400/z" +
            "sdws_pos_consulta_combos/zsdws_pos_consulta_combos_binding")]
        public string WS_POS_web_SapSwQCom_PRD_ZSDWS_POS_CONSULTA_COMBOS {
            get {
                return ((string)(this["WS_POS_web_SapSwQCom_PRD_ZSDWS_POS_CONSULTA_COMBOS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ajeprd.eljuric.com:8000/sap/bc/srt/rfc/sap/zws_facturacion_pos/400/zws_fac" +
            "turacion_pos/zws_facturacion_pos_binding")]
        public string WS_POS_web_Ws_Set_Factura_Sap_PRD_ZWS_FACTURACION_POS {
            get {
                return ((string)(this["WS_POS_web_Ws_Set_Factura_Sap_PRD_ZWS_FACTURACION_POS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ajeprd.eljuric.com:8000/sap/bc/srt/rfc/sap/zws_recuperar_factura_resul1/40" +
            "0/zws_recuperar_factura_resul1/zws_recuperar_factura_resul1_binding")]
        public string WS_POS_web_Ws_Recuperar_Factura_PRD_ZWS_RECUPERAR_FACTURA_RESUL1 {
            get {
                return ((string)(this["WS_POS_web_Ws_Recuperar_Factura_PRD_ZWS_RECUPERAR_FACTURA_RESUL1"]));
            }
        }
    }
}
