//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WS_POS_web.Ws_Creacion_Cliente_N {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    // CODEGEN: No se controló el elemento de extensión WSDL opcional 'Policy' del espacio de nombres 'http://schemas.xmlsoap.org/ws/2004/09/policy'.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ZWS_CREATER_COSTBINDING", Namespace="urn:sap-com:document:sap:soap:functions:mc-style")]
    public partial class ZWS_CREATER_COSTUMER_2010 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ZsdCreateCustomer2010OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ZWS_CREATER_COSTUMER_2010() {
            this.Url = global::WS_POS_web.Properties.Settings.Default.WS_POS_web_Ws_Creacion_Cliente_N_ZWS_CREATER_COSTUMER_2010;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ZsdCreateCustomer2010CompletedEventHandler ZsdCreateCustomer2010Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="urn:sap-com:document:sap:soap:functions:mc-style", ResponseNamespace="urn:sap-com:document:sap:soap:functions:mc-style", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZsdCreateCustomer2010(
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string PaBarr, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string PaBran1, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string PaBrsch, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string PaCelu, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string PaEmail, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string PaExt1, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string PaExt2, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string PaFamst, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string PaFax, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string PaFityp, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string PaKdgrp, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string PaKtokd, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string PaParge, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string PaParh1, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string PaPobl, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string PaPriap, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string PaPrino, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string PaRecco, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string PaRegi, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string PaStcd1, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string PaStcdt, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string PaStr1, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string PaStr2, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string PaStr3, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string PaTel1, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string PaTel2, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string PaTrata, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string PaUcaja, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string PaVkbur) {
            object[] results = this.Invoke("ZsdCreateCustomer2010", new object[] {
                        PaBarr,
                        PaBran1,
                        PaBrsch,
                        PaCelu,
                        PaEmail,
                        PaExt1,
                        PaExt2,
                        PaFamst,
                        PaFax,
                        PaFityp,
                        PaKdgrp,
                        PaKtokd,
                        PaParge,
                        PaParh1,
                        PaPobl,
                        PaPriap,
                        PaPrino,
                        PaRecco,
                        PaRegi,
                        PaStcd1,
                        PaStcdt,
                        PaStr1,
                        PaStr2,
                        PaStr3,
                        PaTel1,
                        PaTel2,
                        PaTrata,
                        PaUcaja,
                        PaVkbur});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ZsdCreateCustomer2010Async(
                    string PaBarr, 
                    string PaBran1, 
                    string PaBrsch, 
                    string PaCelu, 
                    string PaEmail, 
                    string PaExt1, 
                    string PaExt2, 
                    string PaFamst, 
                    string PaFax, 
                    string PaFityp, 
                    string PaKdgrp, 
                    string PaKtokd, 
                    string PaParge, 
                    string PaParh1, 
                    string PaPobl, 
                    string PaPriap, 
                    string PaPrino, 
                    string PaRecco, 
                    string PaRegi, 
                    string PaStcd1, 
                    string PaStcdt, 
                    string PaStr1, 
                    string PaStr2, 
                    string PaStr3, 
                    string PaTel1, 
                    string PaTel2, 
                    string PaTrata, 
                    string PaUcaja, 
                    string PaVkbur) {
            this.ZsdCreateCustomer2010Async(PaBarr, PaBran1, PaBrsch, PaCelu, PaEmail, PaExt1, PaExt2, PaFamst, PaFax, PaFityp, PaKdgrp, PaKtokd, PaParge, PaParh1, PaPobl, PaPriap, PaPrino, PaRecco, PaRegi, PaStcd1, PaStcdt, PaStr1, PaStr2, PaStr3, PaTel1, PaTel2, PaTrata, PaUcaja, PaVkbur, null);
        }
        
        /// <remarks/>
        public void ZsdCreateCustomer2010Async(
                    string PaBarr, 
                    string PaBran1, 
                    string PaBrsch, 
                    string PaCelu, 
                    string PaEmail, 
                    string PaExt1, 
                    string PaExt2, 
                    string PaFamst, 
                    string PaFax, 
                    string PaFityp, 
                    string PaKdgrp, 
                    string PaKtokd, 
                    string PaParge, 
                    string PaParh1, 
                    string PaPobl, 
                    string PaPriap, 
                    string PaPrino, 
                    string PaRecco, 
                    string PaRegi, 
                    string PaStcd1, 
                    string PaStcdt, 
                    string PaStr1, 
                    string PaStr2, 
                    string PaStr3, 
                    string PaTel1, 
                    string PaTel2, 
                    string PaTrata, 
                    string PaUcaja, 
                    string PaVkbur, 
                    object userState) {
            if ((this.ZsdCreateCustomer2010OperationCompleted == null)) {
                this.ZsdCreateCustomer2010OperationCompleted = new System.Threading.SendOrPostCallback(this.OnZsdCreateCustomer2010OperationCompleted);
            }
            this.InvokeAsync("ZsdCreateCustomer2010", new object[] {
                        PaBarr,
                        PaBran1,
                        PaBrsch,
                        PaCelu,
                        PaEmail,
                        PaExt1,
                        PaExt2,
                        PaFamst,
                        PaFax,
                        PaFityp,
                        PaKdgrp,
                        PaKtokd,
                        PaParge,
                        PaParh1,
                        PaPobl,
                        PaPriap,
                        PaPrino,
                        PaRecco,
                        PaRegi,
                        PaStcd1,
                        PaStcdt,
                        PaStr1,
                        PaStr2,
                        PaStr3,
                        PaTel1,
                        PaTel2,
                        PaTrata,
                        PaUcaja,
                        PaVkbur}, this.ZsdCreateCustomer2010OperationCompleted, userState);
        }
        
        private void OnZsdCreateCustomer2010OperationCompleted(object arg) {
            if ((this.ZsdCreateCustomer2010Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZsdCreateCustomer2010Completed(this, new ZsdCreateCustomer2010CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ZsdCreateCustomer2010CompletedEventHandler(object sender, ZsdCreateCustomer2010CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZsdCreateCustomer2010CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZsdCreateCustomer2010CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591